### ISSUE TITLE
Update documentation to use Hooks

### ISSUE THREAD

**Issue by a-zen** [mCodex/react-native-rooster#15]
Hi,

I followed the documentation to [add a toast](https://mcodex.dev/react-native-rooster/docs/addToast) and got the following error:

````
[Unhandled promise rejection: TypeError: (0, _reactNativeRooster.addToast) is not a function. (In '(0, _reactNativeRooster.addToast)({]
````

I then checked the example app in the repository and noticed that the hook **useToast** should be used instead and got it to work.

Would be nice to update the documentation.

**Comment by mCodex** [comment]
> Hi,
> 
> I followed the documentation to [add a toast](https://mcodex.dev/react-native-rooster/docs/addToast) and got the following error:
> 
> ```
> [Unhandled promise rejection: TypeError: (0, _reactNativeRooster.addToast) is not a function. (In '(0, _reactNativeRooster.addToast)({]
> ```
> 
> I then checked the example app in the repository and noticed that the hook **useToast** should be used instead and got it to work.
> 
> Would be nice to update the documentation.

I'm sorry, my mistake. I'll update ASAP

**Comment by mCodex** [comment]
Fixed and published
